import Head from "next/head"
import Button from "components/Button"
import GitHub from "components/icon/GitHub"
import styles from "styles/Home.module.css"
import { useState, useEffect } from "react"
import Avatar from "components/Avatar"
import { loginWithGitHub, onAuthStateChangedTo } from "firebas/client"
import Logo from "../components/icon/Logo"
import AppLayout from "components/Applayout"

export default function Home() {
  const [user, setUser] = useState(undefined)

  useEffect(() => {
    onAuthStateChangedTo(setUser)
  }, [])

  const handleClick = () => {
    loginWithGitHub()
      .then(setUser)
      .catch((err) => {
        console.log(err)
      })
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <section className={styles.section}>
          <Logo className={styles.img} src="/devter-logo.png" alt="logo" />
          <h1 className={styles.h1}>Devter</h1>
          <h2 className={styles.h2}>
            Habla con desarrolladores <br />
            sobre desarrolladores
          </h2>
          <div>
            {user === null && (
              <Button onClick={handleClick}>
                <GitHub fill="#fff" width={24} height={24} />
                Login with GitHub
              </Button>
            )}
            {user && user.avatar && (
              <div>
                <Avatar
                  alt={user.username}
                  src={user.avatar}
                  text={user.username}
                />
              </div>
            )}
          </div>
        </section>
      </AppLayout>
    </>
  )
}
