import Head from "next/head"
import Button from "components/Button"
import GitHub from "components/icon/GitHub"
import styles from "styles/Home.module.css"
import { useEffect } from "react"
import { loginWithGitHub } from "firebas/client"
import Logo from "../components/icon/Logo"
import { useRouter } from "next/router"
import useUser, { USER_STATE } from "hooks/useUser"

export default function Home() {
  const user = useUser()
  const router = useRouter()

  useEffect(() => {
    user && router.replace("/home")
  }, [user])

  const handleClick = () => {
    loginWithGitHub().catch((err) => {
      console.log(err)
    })
  }

  return (
    <>
      <Head>
        <title>Devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <section className={styles.section}>
          <Logo className={styles.img} src="/devter-logo.png" alt="logo" />
          <h1 className={styles.h1}>Devter</h1>
          <h2 className={styles.h2}>
            Habla con desarrolladores <br />
            sobre desarrolladores
          </h2>
          <div>
            {user === USER_STATE.NOT_LOGGED && (
              <Button onClick={handleClick}>
                <GitHub fill="#fff" width={24} height={24} />
                Login with GitHub
              </Button>
            )}
            {user === USER_STATE.NOT_KNOWN && <img src="/spinner.gif" />}
          </div>
        </section>
      
    </>
  )
}
